apiVersion: batch/v1
kind: Job
metadata:
  name: qr-generator-job
spec:
  template:
    spec:
      containers:
      - name: qr-generator-job
        image: yash5090/qr-generator:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
